# Generated by Django 3.2.18 on 2023-04-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0010_alter_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='quanti',
        ),
    ]
