# Generated by Django 3.2.18 on 2023-04-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0011_rename_quantity_orderitem_quanti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quanti',
            new_name='quantity',
        ),
    ]
